{
    "id": "LUCENE-4997",
    "title": "Internal test framework's tests are sensitive to previous test failures and tests.failfast.",
    "details": {
        "components": [],
        "fix_versions": [
            "4.4",
            "6.0"
        ],
        "affect_versions": "None",
        "priority": "Minor",
        "labels": "",
        "type": "Bug",
        "resolution": "Fixed",
        "status": "Closed"
    },
    "description": "",
    "attachments": {},
    "issue_links": {},
    "comments": [
        {
            "date": "2013-05-12T19:44:29+0000",
            "content": "[trunk commit] dweiss\nhttp://svn.apache.org/viewvc?view=revision&revision=1481634\n\nLUCENE-4997: Internal test framework's tests are sensitive to previous test failures and tests.failfast. ",
            "author": "Commit Tag Bot",
            "id": "comment-13655621"
        },
        {
            "date": "2013-05-12T19:48:24+0000",
            "content": "[branch_4x commit] dweiss\nhttp://svn.apache.org/viewvc?view=revision&revision=1481636\n\nLUCENE-4997: Internal test framework's tests are sensitive to previous test failures and tests.failfast. ",
            "author": "Commit Tag Bot",
            "id": "comment-13655623"
        },
        {
            "date": "2013-07-23T18:37:05+0000",
            "content": "Bulk close resolved 4.4 issues ",
            "author": "Steve Rowe",
            "id": "comment-13716743"
        }
    ]
}