{
    "id": "SOLR-2803",
    "title": "NPE in FacetComponent",
    "details": {
        "affect_versions": "3.3,                                            3.4",
        "status": "Closed",
        "fix_versions": [],
        "components": [],
        "type": "Bug",
        "priority": "Major",
        "labels": "",
        "resolution": "Cannot Reproduce"
    },
    "description": "On a call to my multicore setup (with 'activity' being one of my cores):\n\n/solr/activity/select/?q=:&fq=bucket:1000&fq=dma:%22Albuquerque%22&version=2.2&start=0&rows=0&facet=on&facet.date=time&facet.date.start=2011-02-01T04:00:00Z&facet.date.end=2011-06-11T00:00:00Z&facet.date.gap=%2B1HOUR&wt=json&qt=grid\n\nI get a NPE in the FacetComponent patch.\n\nSEVERE: java.lang.NullPointerException\n        at org.apache.solr.handler.component.FacetComponent.countFacets(FacetComponent.java:347)\n        at org.apache.solr.handler.component.FacetComponent.handleResponses(FacetComponent.java:257)\n        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:289)\n        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:129)\n        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1368)\n        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:356)\n        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:252)\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)\n        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)\n        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)\n        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:462)\n        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:164)\n        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)\n        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:851)\n        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)\n        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:405)\n        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:278)\n        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:515)\n        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:300)\n        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)\n        at java.lang.Thread.run(Thread.java:619)\n\nWith a 500 error response.\n\nHere is the qt=grid RequestHandler definition in the solrconfig.xml\n  <requestHandler name=\"grid\" class=\"solr.SearchHandler\">\n    <lst name=\"defaults\">\n       <str name=\"echoParams\">explicit</str>\n       <int name=\"rows\">10</int>\n       <str name=\"shards\">core-dev-01.example.com:8080/jiwire/activity,core-dev-02.example.com:8080/jiwire/activity,core-dev-03.example.com:8080/jiwire/activity,core-dev-01.example.com:8080/jiwire/activity,core-dev-01.example.com:8080/jiwire/activity2,core-dev-02.example.com:8080/jiwire/activity2,core-dev-03.example.com:8080/jiwire/activity2,core-dev-01.example.com:8080/jiwire/activity2,core-dev-01.example.com:8080/jiwire/activity3,core-dev-02.example.com:8080/jiwire/activity3,core-dev-03.example.com:8080/jiwire/activity3,core-dev-01.example.com:8080/jiwire/activity3,core-dev-01.example.com:8080/jiwire/activity4,core-dev-02.example.com:8080/jiwire/activity4,core-dev-03.example.com:8080/jiwire/activity4,core-dev-01.example.com:8080/jiwire/activity4</str>\n    </lst>\n  </requestHandler>",
    "attachments": {
        "FacetComponent.patch": "https://issues.apache.org/jira/secure/attachment/12497384/FacetComponent.patch"
    },
    "issue_links": {},
    "comments": [
        {
            "author": "Fi",
            "id": "comment-13118931",
            "date": "2011-10-01T23:21:48+0000",
            "content": "This patch (FacetComponent.patch) gets past the NPE.\n\nThere is probably something more fundamentally wrong with the events leading up to the error, but at least this patch lets me get past the problem. "
        },
        {
            "author": "Hoss Man",
            "id": "comment-13150908",
            "date": "2011-11-15T23:54:47+0000",
            "content": "I'm more then a tad confused by this issue..\n\nThe first thing that jumps out at me is that the issue summary (and paths attached patch) suggest that this problem was encountered against Solr 3.4, but the example URL is doing a distrubuted query against multiple shards using date faceting \u2013 distributed support for date faceting didn't exist in Solr 3.4, and still doesn't exist anywhere on the 3x branch, it is only on trunk (see SOLR-1709).  So I'm not really sure what the point of this example URL is at all? even w/o the NPE it doesn't seem like it will do anything useful.\n\nThat lead me to suspect that perhaps there was a glitch in the 3x faceting code, where requesting \"facet=true\" on a distributed query, w/o any facet fields might cause shards to return empty facet results, which might lead to the NPE in question.  But when I did some adhoc testing of this using Solr 3.4, I couldn't reproduce.  facet=true with no faceting, facet=true with date faceting but only one shard has docs using that date field, etc... none of the situations i could think of would cause this problem of the bitset not being initialized.\n\nI then tried all of these sorts of adhoc testing again using trunk (where distributed date faceting is supported) and i still couldn't reproduce the failure.\n\nFi: exactly which version of Solr are you using?  is it the same on every shard? if it is a 3x version what exactly is the behavior you are expecting/getting with the date faceting (even after your work-around patch) .. w/o this patch did you get the failure consistently? can you post the details of what requests get logged on each of your shards when executing one of these queries that fails and what those individual shards return when you execute those logged queries against them manually?\n\n\n\n "
        },
        {
            "author": "Alexandre Rafalovitch",
            "id": "comment-15547548",
            "date": "2016-10-05T04:12:17+0000",
            "content": "Ancient issue that could not be reproduced at a time. If a similar problem happens with recent version of Solr, a new issue can be created with updated details/stack-trace. "
        }
    ]
}