{
    "id": "SOLR-4186",
    "title": "QueryComponent NPE",
    "details": {
        "affect_versions": "4.0,                                            6.0",
        "status": "Resolved",
        "fix_versions": [],
        "components": [
            "search",
            "SolrCloud"
        ],
        "type": "Bug",
        "priority": "Major",
        "labels": "",
        "resolution": "Fixed"
    },
    "description": "Similar to SOLR-4049, the QueryComponent throws the following NPE in case a distributed search fails for some reason. This bug has been around for at least one or two weeks.\n\n\n2012-12-14 10:00:41,611 ERROR [solr.servlet.SolrDispatchFilter] - [http-8080-exec-5] - : null:java.lang.NullPointerException\n        at org.apache.solr.handler.component.QueryComponent.returnFields(QueryComponent.java:967)\n        at org.apache.solr.handler.component.QueryComponent.handleRegularResponses(QueryComponent.java:629)\n        at org.apache.solr.handler.component.QueryComponent.handleResponses(QueryComponent.java:604)\n        at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:311)\n        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:146)\n        at org.apache.solr.core.SolrCore.execute(SolrCore.java:1818)\n        at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:479)\n        at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:279)\n        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)\n        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)\n        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)\n        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)\n        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)\n        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)\n        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)\n        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)\n        at org.apache.coyote.http11.Http11NioProcessor.process(Http11NioProcessor.java:889)\n        at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:744)\n        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:2274)\n        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)\n        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)\n        at java.lang.Thread.run(Thread.java:662)",
    "attachments": {},
    "issue_links": {},
    "comments": [
        {
            "author": "Trey Hyde",
            "id": "comment-13544531",
            "date": "2013-01-05T02:34:54+0000",
            "content": "I get same thing in occasionally in 4.0 GA (currently marked as affects 5.0 only) "
        },
        {
            "author": "Patanachai Tangchaisin",
            "id": "comment-13601674",
            "date": "2013-03-13T21:26:38+0000",
            "content": "I also got this problem.\nIn my case, it occurs only when there is a error when Solr cannot retrieve a field value (shard purpose = 0x40) "
        },
        {
            "author": "Patanachai Tangchaisin",
            "id": "comment-13627591",
            "date": "2013-04-10T08:02:52+0000",
            "content": "After digging into this, a real cause of a problem is when shards.tolerant = true and there is a Exception during retrieving field request. \n\nA solution is depend on how client expect Solr to behave when error occurs\n\n\tIf client is OK if Solr returns less document than request (rows parameter) then skipping a shard request which has an error can be a solution.\n\tIf client must have a same number of document as rows, then retrying would be another options\n\tOtherwise, wrapping this exception and throw to client with a proper error message.\n\n "
        },
        {
            "author": "Steve Rowe",
            "id": "comment-13717421",
            "date": "2013-07-23T18:48:11+0000",
            "content": "Bulk move 4.4 issues to 4.5 and 5.0 "
        },
        {
            "author": "Uwe Schindler",
            "id": "comment-13971128",
            "date": "2014-04-16T12:57:14+0000",
            "content": "Move issue to Solr 4.9. "
        },
        {
            "author": "Sunil Srinivasan",
            "id": "comment-13989106",
            "date": "2014-05-04T19:44:51+0000",
            "content": "I am trying to look into this issue.  Could you folks give me steps to reproduce the same\n\nThe query I am running is this\n\nhttp://localhost:8983/solr/collection1/select?q=cat=electronics&shards=localhost:7574/solr,localhost:8983/solr&shards.info=true&shards.tolerant=true&query=true&fl=cat "
        },
        {
            "author": "Patanachai Tangchaisin",
            "id": "comment-13989156",
            "date": "2014-05-04T21:16:22+0000",
            "content": "Sunil Srinivasan\nI think you need a to create a special handler/component to reproduce this. \nFrom the 2 shards, one shard should have this customization. When the request comes in as a retrieving field value request (shard purpose = 0x40), the shard should throw an exception.\n\nTo be specific for your request, localhost:7574 should have the customization and always throws exception when the request purpose is retrieving field value. The NPE exception will be happening at localhost:8983 "
        },
        {
            "author": "Sunil Srinivasan",
            "id": "comment-13992000",
            "date": "2014-05-07T16:58:42+0000",
            "content": "Patanachai Tangchaisin\n\nI am unable to still reproduce this \n\nI configured the second instance to return a 500 and when I call the query like this\n\nhttp://localhost:8983/solr/collection1/query?q=cat:electronics&shards=localhost:7574/solr,localhost:8983/solr&query=true&shards.tolerant=true&shards.info=true&fl=cat,score\n\nI do get partial results and 8983 doesn't throw NPE\n\n\n21362795 [qtp1458849419-13] INFO  org.apache.solr.core.SolrCore  \u2013 [collection1] webapp=/solr path=/select params=\nUnknown macro: {df=text&distrib=false&fl=id,score&query=true&start=0&fsv=true&shards.info=true&shard.url=localhost} \n status=500 QTime=2\n21362796 [qtp1458849419-13] ERROR org.apache.solr.servlet.SolrDispatchFilter  \u2013 null:java.lang.NullPointerException\n\tat org.apache.solr.handler.component.ResponseBuilder.getQueryCommand(ResponseBuilder.java:394)\n\tat org.apache.solr.handler.component.QueryComponent.process(QueryComponent.java:261)\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:221)\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)\n\tat org.apache.solr.core.SolrCore.execute(SolrCore.java:1964)\n\nOn 8983\n\n\n21543999 [qtp1458849419-19] INFO  org.apache.solr.core.SolrCore  \u2013 [collection1] webapp=/solr path=/select params=\nUnknown macro: {df=text&distrib=false&fl=id,score&query=true&start=0&fsv=true&shards.info=true&shard.url=localhost} \n hits=9 status=0 QTime=1\n21544006 [qtp1458849419-19] INFO  org.apache.solr.core.SolrCore  \u2013 [collection1] webapp=/solr path=/select params=\nUnknown macro: {df=text&distrib=false&fl=cat,score&fl=id&query=true&shards.info=true&shard.url=localhost} \n status=0 QTime=1\n21544007 [qtp1458849419-16] INFO  org.apache.solr.core.SolrCore  \u2013 [collection1] webapp=/solr path=/query params=\nUnknown macro: {q=cat} \n hits=9 status=0 QTime=14 "
        },
        {
            "author": "Patanachai Tangchaisin",
            "id": "comment-14052732",
            "date": "2014-07-05T00:09:10+0000",
            "content": "May be this is fixed by SOLR-6223?\nSince the cause of the problem seems to be the same shards.tolerant=true. "
        },
        {
            "author": "Shalin Shekhar Mangar",
            "id": "comment-14052795",
            "date": "2014-07-05T05:03:38+0000",
            "content": "Yes, this is fixed by SOLR-6223. We have a test which demonstrates a failure in the GET_FIELDS phase. I'll mark this issue as a duplicate. "
        }
    ]
}