{
    "id": "SOLR-7071",
    "title": "SolrCore init failure handling preempts SolrCloud's failover support.",
    "details": {
        "components": [
            "SolrCloud"
        ],
        "type": "Bug",
        "labels": "",
        "fix_versions": [],
        "affect_versions": "None",
        "status": "Open",
        "resolution": "Unresolved",
        "priority": "Major"
    },
    "description": "If you are using a load balancer or direct querying and one of your replicas can't load a core for some reason (init failure due to index corruption or bad config or whatever), if a query for a collection hit's that node, it won't get proxied to another node for good failover - you will get an error returned about the init failure.",
    "attachments": {},
    "issue_links": {},
    "comments": [
        {
            "date": "2017-01-27T21:29:49+0000",
            "author": "Cassandra Targett",
            "content": "I believe SOLR-7069 is the same problem. ",
            "id": "comment-15843518"
        }
    ]
}