{
    "id": "SOLR-2668",
    "title": "DIH - multithreaded does not rollback on errors from EntityProcessor",
    "details": {
        "affect_versions": "3.3",
        "status": "Resolved",
        "fix_versions": [],
        "components": [
            "contrib - DataImportHandler"
        ],
        "type": "Bug",
        "priority": "Major",
        "labels": "",
        "resolution": "Fixed"
    },
    "description": "If the EntityProcessor of a subentity throws an Exception in its init() Method, DocBuilder logs \"Import completed successfully\" and calls commit instead of calling rollback.",
    "attachments": {
        "SOLR-2668.patch": "https://issues.apache.org/jira/secure/attachment/12487374/SOLR-2668.patch"
    },
    "issue_links": {},
    "comments": [
        {
            "author": "Frank Wesemann",
            "id": "comment-13069294",
            "date": "2011-07-21T23:47:08+0000",
            "content": "patch for the unittest to clarify the problem "
        },
        {
            "author": "Shalin Shekhar Mangar",
            "id": "comment-13070767",
            "date": "2011-07-25T21:19:51+0000",
            "content": "Thanks for the test Frank. There are more problems. In single thread mode, an error causes a rollback but in threaded mode, a commit is called. "
        },
        {
            "author": "Shalin Shekhar Mangar",
            "id": "comment-13090182",
            "date": "2011-08-24T12:48:46+0000",
            "content": "I was looking at this problem again today. The onError attributes are not used to deal with exceptions from EntityProcessor.init() method. They are only used for reading rows, applying transformers and inserting documents into Solr.\n\nThe real problem was that in multi-threaded mode, the exceptions from EntityProcessor.init were being eaten up so a commit was called instead of rolling back the changes. I've fixed that to re-throw the exception up the hierarchy. "
        },
        {
            "author": "Shalin Shekhar Mangar",
            "id": "comment-13090937",
            "date": "2011-08-25T11:11:54+0000",
            "content": "Fixed a bug in the tests. The index was not being emptied in tearDown so even after rollback, the index had 4 documents.\n\nJust to show that multi-threaded does honor the onError attribute, I've added a test which uses a transformer which always fails.\n\nThe older two tests are used to demonstrate that both multi-threaded and serial mode show the same characteristic for a failing entity processor. "
        },
        {
            "author": "Shalin Shekhar Mangar",
            "id": "comment-13090947",
            "date": "2011-08-25T11:27:04+0000",
            "content": "Committed revision 1161505 on trunk and 1161510 on branch_3x. "
        }
    ]
}