{
    "id": "SOLR-5945",
    "title": "Add retry for zookeeper reconnect failure",
    "details": {
        "affect_versions": "4.7",
        "status": "Open",
        "fix_versions": [],
        "components": [
            "SolrCloud"
        ],
        "type": "Improvement",
        "priority": "Major",
        "labels": "",
        "resolution": "Unresolved"
    },
    "description": "We had some network issue where we temporarily lost connection and DNS. The zookeeper client properly triggered the watcher. However, when trying to reconnect, this following Exception is thrown:\n\n2014-03-27 17:24:46,882 ERROR [main-EventThread] SolrException.java (line 121) :java.net.UnknownHostException: <host name (scrubbed)>: Name or service not known\n        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)\n        at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:866)\n        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1258)\n        at java.net.InetAddress.getAllByName0(InetAddress.java:1211)\n        at java.net.InetAddress.getAllByName(InetAddress.java:1127)\n        at java.net.InetAddress.getAllByName(InetAddress.java:1063)\n        at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:60)\n        at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:445)\n        at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:380)\n        at org.apache.solr.common.cloud.SolrZooKeeper.<init>(SolrZooKeeper.java:41)\n        at org.apache.solr.common.cloud.DefaultConnectionStrategy.reconnect(DefaultConnectionStrategy.java:53)\n        at org.apache.solr.common.cloud.ConnectionManager.process(ConnectionManager.java:147)\n        at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:519)\n        at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:495)\n\nI tried to look at the code and it seems that there'd be no further retries to connect to Zookeeper, and the node is basically left in a bad state and will not recover on its own. (Please correct me if I'm reading this wrong.) Thinking about it, this is probably fair, since normally you wouldn't expect retries to fix an \"unknown host\" issue (even though in our case it would have) but I'm wondering what we should do to handle this situation if it happens again in the future.\n\nAny advice is appreciated.\n\n\n\nFrom Mark Miller:\nWe don\u2019t currently retry, but I don\u2019t think it would hurt much if we did - at least briefly.\n\nIf you want to file a JIRA issue, that would be the best way to get it in a future release.",
    "attachments": {},
    "issue_links": {},
    "comments": []
}