{
    "id": "SOLR-9011",
    "title": "SolrJ JDBC - Ensure that Python JayDeBeApi works with SolrJ JDBC",
    "details": {
        "components": [
            "SolrJ"
        ],
        "type": "Sub-task",
        "labels": "",
        "fix_versions": [
            "6.1"
        ],
        "affect_versions": "6.0",
        "status": "Closed",
        "resolution": "Fixed",
        "priority": "Major"
    },
    "description": "Python with JayDeBeApi enables connections to JDBC sources.",
    "attachments": {},
    "issue_links": {},
    "comments": [
        {
            "date": "2016-04-19T16:10:40+0000",
            "author": "Kevin Risden",
            "content": "JayDeBeApi fails since it requires a prepare statement to execute the statements. JayDeBeApi currently doesn't display the underlying exception so had to pull the following from jaydebeapi/_init_.py.\n\n\ndef execute(self, operation, parameters=None):\n        if self._connection._closed:\n            raise Error()\n        if not parameters:\n            parameters = ()\n        self._close_last()\n        self._prep = self._connection.jconn.prepareStatement(operation)\n        self._set_stmt_parms(self._prep, parameters)\n        try:\n            is_rs = self._prep.execute()\n        except:\n            _handle_sql_exception()\n\n ",
            "id": "comment-15248062"
        },
        {
            "date": "2016-04-20T16:02:09+0000",
            "author": "Kevin Risden",
            "content": "Resolving since SOLR-8809 was closed and manual testing shows Python with JayDeBeApi was able to connect to Solr. ",
            "id": "comment-15250147"
        }
    ]
}